### PR TITLE
General tests for spectra

### PR DESCRIPTION
**Pull request by chillenzer**
This small PR provides some general tests for the spectra, namely orthonormality of the eigenfunctions (in real space), identity of back and forth transformation and unitarity of the transformation.

These are general properties that hold completely independent of the concrete spectrum at hand (as long as the spectrum's interface is implemented in a way to cope with the terse broadcasting syntax used). So they should be easily generalisable by adding more `TEST_DATA`.

I took the liberty to make the tests pass by adjusting the conventions in `spectra/derivative_1D.py`.

### CODE REVIEW

**Comment by Mayank447** [comment]
None of the tests are passing. Also in some of the tests there is a mismatch in the number of lattice points and the boundary length

**Comment by chillenzer** [comment]
No, don't do this! This is a separate PR because it is concerned with an independent concern. We should not mix this up. Please remove the code from your PR again and add a proper review here.

**Comment by Mayank447** [comment]
Cool, couple of minor changes in all files
input_space -> input_basis
output_space -> output_basis

Otherwise the tests are throwing an error

**Comment by chillenzer** [comment]
Closes #13.

**Pull request merged**
